### ISSUE TITLE
charset=UTF-8 appending to Content-Type for client defined in xml

### ISSUE THREAD

**Issue by mikeloll** [christophd/citrus#246] opened 2017-05-25 18:45 UTC
I may have found a bug..

When configuring an http-client using the XML syntax, if you set the content-type attribute and then use the client in a Java dsl call, it will append `charset=UTF-8` to the content type.

If you call `contentType()` on the http builder and give it your content type (with no charset parameter) it will *not* append the charset.

I would expect that what is configured in the xml would be honored and not modified.

**Comment by mikeloll** [comment] 2017-05-25 18:45
I initially posted this as a question on stackoverflow: https://stackoverflow.com/questions/44187462/remove-charset-in-content-type-header-in-citrus.

**Comment by christophd** [comment] 2017-05-28 14:22
I am confused here. I would expect the test case DSL send operation to always overwrite the XML component configuration. So if you set a content type in the send operation via Java DSL the constructed message should have this content type setting. If you not set the content type in Java DSL the default content type specified in XML should be applied.

**Comment by mikeloll** [comment] 2017-05-30 12:42
That is what I would expect, but that is not what I am seeing.

**Comment by christophd** [comment] 2017-07-04 15:27
I have the following client endpoint defined:

    <citrus-http:client id="httpClient"
                 request-url="http://localhost:8080/test"
                 request-method="POST"
                 content-type="text/xml"/>

Content-Type is set to "text/xml". I use this client in Java DSL:

    http(action -> action.client("httpClient")
                .send()
                .get());

I get following request:

    HTTP/1.1 GET /test
    Host:localhost:8080
    Accept:text/plain, application/json, application/*+json, */*
    Content-Type:text/xml;charset=UTF-8

Notice: The `charset=UTF-8` is automatically added with underlying Http client implementation.
When I overwrite the Content-Type in Java DSL:

    http(action -> action.client("httpClient")
                .send()
                .get()
                .contentType("text/xml"));

I get following request:

    HTTP/1.1 GET /test
    Host:localhost:8072
    Accept:text/plain, application/json, application/*+json, */*
    Content-Type:text/xml

Notice: Content-Type has been added as-is defined in Java DSL. So Java DSL overwrites XML endpoint configuration. This is a total expected behavior to me. Someone could argue that the charset is added automatically but this would be another question.

About to close this issue - any objections?

**Comment by christophd** [comment] 2017-07-04 15:42
Sorry I have to correct some of my previous statements. The charset is not added with underlying Http client implementation but within Citrus Http message converter. This is because the charset is a separate attribute on the http client component and defaults to "UTF-8".

So I have added the opportunity to set the charset to empty string in http client configuration:

    <citrus-http:client id="httpClient"
             request-url="http://localhost:8080/test"
             request-method="POST"
             charset=""
             content-type="text/xml"/>

After that the charset is not automatically added to the Content-Type header as you expected in the first place. Sorry again!

**Closed** 2017-07-04 15:47 UTC
Labels: bug
